snowflake:
  account_identifier: nivstjq-xj32310
  username: bao
  password: XgZkorTjfzRvMX2AY7vz
  warehouse: ""
  database:
    name: ""
  schema: ""

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    mysql:
      username: springuser
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_example
    snowflake:
      url: jdbc:snowflake://${snowflake.account_identifier}.snowflakecomputing.com/?user=${snowflake.username}&password=${snowflake.password}&warehouse=${snowflake.warehouse}&db=${snowflake.database.name}&schema=${snowflake.schema}
      driver-class-name: net.snowflake.client.jdbc.SnowflakeDriver
logging:
  level:
    root: debug
