springdoc:
  custom:
    authentication:
      enabled: true
      methods:
        - BASIC
#        - BEARER
#      - OAUTH2
jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

